version: 1.0.{build}
branches:
  only:
  - master
  - engauge28_EditModeLayout
  - engauge333_V2
  - phantomJsImagesQuality
  - release_candidate_1.6
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  project: Checkbox.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
test: off
deploy:
- provider: Environment
  name: engdev01