version: 1.0.{build}
branches:
  only:
  - master
build_script:
- cmd: >-
    cd c:\Projects\engauge-provisioning

    dir /w

    7z a ../dist.zip *


    appveyor PushArtifact ..\dist.zip -Verbosity Normal -DeploymentName ProvisioningWeb.zip
test: off
deploy:
- provider: Environment
  name: selfserve