//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Forms.Surveys.Controls {
    
    
    public partial class LanguageSettings {
        
        /// <summary>
        /// _languagesRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater _languagesRepeater;
        
        /// <summary>
        /// availablePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel availablePanel;
        
        /// <summary>
        /// _availableLanguages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList _availableLanguages;
        
        /// <summary>
        /// _addLanguageBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton _addLanguageBtn;
        
        /// <summary>
        /// noneAvailablePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel noneAvailablePanel;
        
        /// <summary>
        /// _noneAvailableLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _noneAvailableLbl;
        
        /// <summary>
        /// _defaultLanguageLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _defaultLanguageLbl;
        
        /// <summary>
        /// _defaultLanguage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList _defaultLanguage;
        
        /// <summary>
        /// _languageSelectionLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _languageSelectionLbl;
        
        /// <summary>
        /// _languageSelectList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageDropDownList _languageSelectList;
        
        /// <summary>
        /// _languageSelectOptionPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder _languageSelectOptionPlace;
        
        /// <summary>
        /// _optionLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _optionLbl;
        
        /// <summary>
        /// _variableNameTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _variableNameTxt;
        
        /// <summary>
        /// _browserDetectionUnsuccessOptionPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder _browserDetectionUnsuccessOptionPlace;
        
        /// <summary>
        /// _browserOptionLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _browserOptionLbl;
        
        /// <summary>
        /// _browserDetectionUnsuccessOption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageDropDownList _browserDetectionUnsuccessOption;
    }
}
