//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Forms.Surveys.Reports.Controls.ItemRenderers.ReportEditor {
    
    
    public partial class GovernancePrioritySummary {
        
        /// <summary>
        /// _basicConfig control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Reports.Controls.ItemRenderers.ReportEditor.BasicConfiguration _basicConfig;
        
        /// <summary>
        /// _governancePriorityGraph control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Controls.Charts.GovernancePrioritySummary _governancePriorityGraph;
    }
}
