//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Settings {
    
    
    public partial class Branding {
        
        /// <summary>
        /// _selectedColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _selectedColor;
        
        /// <summary>
        /// dynamicSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel dynamicSettings;
        
        /// <summary>
        /// _headerType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList _headerType;
        
        /// <summary>
        /// _logoOptionsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _logoOptionsPanel;
        
        /// <summary>
        /// _logoImageSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Controls.ItemEditors.ImageSelector _logoImageSelector;
        
        /// <summary>
        /// _textPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _textPanel;
        
        /// <summary>
        /// _headerText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _headerText;
        
        /// <summary>
        /// _fontName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.Styles.XmlBoundDropDownList _fontName;
        
        /// <summary>
        /// _fontStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.Styles.XmlBoundDropDownList _fontStyle;
        
        /// <summary>
        /// _fontSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.Styles.XmlBoundDropDownList _fontSize;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new CheckboxWeb.Dialog Master {
            get {
                return ((CheckboxWeb.Dialog)(base.Master));
            }
        }
    }
}
