//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Settings {
    
    
    public partial class Exceptions {
        
        /// <summary>
        /// MultiLanguageLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel MultiLanguageLabel2;
        
        /// <summary>
        /// _deleteSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Controls.Button.CheckboxButton _deleteSelected;
        
        /// <summary>
        /// _deleteAllBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Controls.Button.CheckboxButton _deleteAllBtn;
        
        /// <summary>
        /// _exceptionsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView _exceptionsGrid;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new CheckboxWeb.Dialog Master {
            get {
                return ((CheckboxWeb.Dialog)(base.Master));
            }
        }
    }
}
