//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Settings {
    
    
    public partial class SearchSettings {
        
        /// <summary>
        /// _searchAccessibleObjectExpPeriodSeconds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _searchAccessibleObjectExpPeriodSeconds;
        
        /// <summary>
        /// _searchAccessibleObjectExpPeriodSecondsValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator _searchAccessibleObjectExpPeriodSecondsValidator;
        
        /// <summary>
        /// _searchResultsExpPeriodSeconds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _searchResultsExpPeriodSeconds;
        
        /// <summary>
        /// _searchResultsExpPeriodSecondsValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator _searchResultsExpPeriodSecondsValidator;
        
        /// <summary>
        /// _searchPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _searchPageSize;
        
        /// <summary>
        /// _searchPageSizeValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator _searchPageSizeValidator;
        
        /// <summary>
        /// _searchMaxResultRecordsPerObjectType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _searchMaxResultRecordsPerObjectType;
        
        /// <summary>
        /// _searchMaxResultRecordsPerObjectTypeValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator _searchMaxResultRecordsPerObjectTypeValidator;
        
        /// <summary>
        /// _searchCachePeriodDays control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _searchCachePeriodDays;
        
        /// <summary>
        /// _searchCachePeriodDaysValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator _searchCachePeriodDaysValidator;
        
        /// <summary>
        /// _objectTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Settings.Controls.SearchObjects _objectTypes;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new CheckboxWeb.Dialog Master {
            get {
                return ((CheckboxWeb.Dialog)(base.Master));
            }
        }
    }
}
