//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Forms.Surveys.Reports.Controls.ItemEditors {
    
    
    public partial class GovernancePrioritySummary {
        
        /// <summary>
        /// _currentTabIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _currentTabIndex;
        
        /// <summary>
        /// _activeDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Controls.ItemActiveDisplay _activeDisplay;
        
        /// <summary>
        /// _previewPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder _previewPlace;
        
        /// <summary>
        /// _ruleDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Controls.ItemConditionsRuleDislpay _ruleDisplay;
        
        /// <summary>
        /// _sourceItemSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Reports.Controls.ItemEditors.SourceItemSelector _sourceItemSelector;
        
        /// <summary>
        /// _itemBehavior control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Reports.Controls.ItemEditors.GovernancePrioritySummaryItemOptions _itemBehavior;
        
        /// <summary>
        /// _appearanceEditorPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder _appearanceEditorPlace;
        
        /// <summary>
        /// _conditionEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Controls.ItemConditionEditor _conditionEditor;
    }
}
