//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Forms.Surveys.Reports.Controls.AppearanceEditors {
    
    
    public partial class ANALYSIS_GRADIENT_COLOR_DIRECTOR_SKILLS_MATRIX {
        
        /// <summary>
        /// _directorAveragesLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _directorAveragesLabel;
        
        /// <summary>
        /// _directorAverages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox _directorAverages;
        
        /// <summary>
        /// titleSizeLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel titleSizeLbl;
        
        /// <summary>
        /// _titleSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageDropDownList _titleSize;
        
        /// <summary>
        /// fontLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel fontLbl;
        
        /// <summary>
        /// _font control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageDropDownList _font;
        
        /// <summary>
        /// _gridLineLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _gridLineLabel;
        
        /// <summary>
        /// _gridLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox _gridLine;
        
        /// <summary>
        /// _itemColumnHeaderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _itemColumnHeaderLabel;
        
        /// <summary>
        /// _itemColumnHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _itemColumnHeader;
        
        /// <summary>
        /// __averagesColumnHeaderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel @__averagesColumnHeaderLabel;
        
        /// <summary>
        /// _averagesColumnHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _averagesColumnHeader;
        
        /// <summary>
        /// _ratingDetailsHeaderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _ratingDetailsHeaderLabel;
        
        /// <summary>
        /// _ratingDetailsHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _ratingDetailsHeader;
        
        /// <summary>
        /// _summaryHeaderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _summaryHeaderLabel;
        
        /// <summary>
        /// _summaryHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _summaryHeader;
    }
}
