//===============================================================================
// Prezza Technologies Application Framework
// Copyright © Checkbox Survey Inc  All rights reserved.
// Contains software or other content adapted from Microsoft patterns & practices Enterprise Library, © 2006 Microsoft Corporation. All rights reserved.
//===============================================================================
using System;

using Prezza.Framework.Configuration;

namespace Prezza.Framework.ExceptionHandling
{
	/// <summary>
	/// Interface that exception handlers must implement.
	/// </summary>
	public interface IExceptionHandler : IConfigurationProvider
	{
		/// <summary>
		/// Get/Set the current exception policy name.
		/// </summary>
		string CurrentPolicyName{get; set;}

		/// <summary>
		/// Get/Set the typeName of the current exception.
		/// </summary>
		string CurrentExceptionTypeName{get; set;}

		/// <summary>
		/// Handle an exception with the specified policy and instance id.
		/// </summary>
		/// <param name="exception">Exception to handle.</param>
		/// <param name="policyName">Exception policy in use.</param>
		/// <param name="handlingInstanceId">Exception instance id.</param>
		/// <returns>New exception generated by a handler as specified in the configuration.</returns>
		Exception HandleException(Exception exception, string policyName, Guid handlingInstanceId);
	}
}
