//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Xheo.Licensing.ExternalActivationServer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Prezza Activation ServerSoap", Namespace="http://www.prezzatech.com/support/members/licensing")]
    public partial class PrezzaActivationServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LicenseCultureSoapHeader licenseCultureSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback ActivateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PrezzaActivationServer() {
            this.Url = "http://www.prezzatech.com/support/members/licensing/UltimateSurveyActivationServi" +
                "ce.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LicenseCultureSoapHeader LicenseCultureSoapHeaderValue {
            get {
                return this.licenseCultureSoapHeaderValueField;
            }
            set {
                this.licenseCultureSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActivateCompletedEventHandler ActivateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LicenseCultureSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prezzatech.com/support/members/licensing/Activate", RequestNamespace="http://www.prezzatech.com/support/members/licensing", ResponseNamespace="http://www.prezzatech.com/support/members/licensing", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Activate(string licenseXml, string keys, string profileHash) {
            object[] results = this.Invoke("Activate", new object[] {
                        licenseXml,
                        keys,
                        profileHash});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginActivate(string licenseXml, string keys, string profileHash, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Activate", new object[] {
                        licenseXml,
                        keys,
                        profileHash}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndActivate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateAsync(string licenseXml, string keys, string profileHash) {
            this.ActivateAsync(licenseXml, keys, profileHash, null);
        }
        
        /// <remarks/>
        public void ActivateAsync(string licenseXml, string keys, string profileHash, object userState) {
            if ((this.ActivateOperationCompleted == null)) {
                this.ActivateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateOperationCompleted);
            }
            this.InvokeAsync("Activate", new object[] {
                        licenseXml,
                        keys,
                        profileHash}, this.ActivateOperationCompleted, userState);
        }
        
        private void OnActivateOperationCompleted(object arg) {
            if ((this.ActivateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateCompleted(this, new ActivateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prezzatech.com/support/members/licensing")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.prezzatech.com/support/members/licensing", IsNullable=false)]
    public partial class LicenseCultureSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string cultureNameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string CultureName {
            get {
                return this.cultureNameField;
            }
            set {
                this.cultureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ActivateCompletedEventHandler(object sender, ActivateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591