//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxWeb.Forms.Surveys.Controls.ItemEditors {
    
    
    public partial class SliderOptionsEditor {
        
        /// <summary>
        /// _numberRangeWarningPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _numberRangeWarningPanel;
        
        /// <summary>
        /// _numberRangeWarningLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Checkbox.Web.UI.Controls.MultiLanguageLabel _numberRangeWarningLbl;
        
        /// <summary>
        /// _optionsEditorPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _optionsEditorPanel;
        
        /// <summary>
        /// _optionTabIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _optionTabIndex;
        
        /// <summary>
        /// _newTabIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox _newTabIndex;
        
        /// <summary>
        /// _tabChangeBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton _tabChangeBtn;
        
        /// <summary>
        /// _optionsEntry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Controls.ItemEditors.SliderOptionsNormalEntry _optionsEntry;
        
        /// <summary>
        /// _quickEntry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CheckboxWeb.Forms.Surveys.Controls.ItemEditors.OptionsQuickEntry _quickEntry;
    }
}
